Upgrade Dockerfile to use node:16-alpine
The existing build failed due to node:0.10 being very old.

Error: "No compatible version found: cz-conventional-changelog@'>=3.1.0 <4.0.0'"

Switching from `node:0.10-onbuild` to `node:16-alpine` required updates to the
Dockerfile, adding steps to install dependencies and copy the source code in to
the image itself. These are steps that `onbuild` performed for us automatically

The Dockerfile was also updated to use `MOCKBIN_REDIS` rather than the
`npm config set` method of enabling Redis as the `npm config set` method no
longer seems to work